# Generated by Django 4.0.6 on 2022-09-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matzips', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('bio', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('social_mode', models.BooleanField(default=False)),
                ('desired_gender', models.CharField(blank=True, default='', max_length=1, null=True)),
                ('desired_major', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('min_people', models.IntegerField(default=1)),
                ('max_people', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.CharField(default='00시간00분', max_length=15)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('matzip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matzips.matzip')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchings.matching')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
