# Generated by Django 4.0.6 on 2022-07-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matzips', '0002_alter_matzip_name'),
        ('profiles', '0001_initial'),
        ('matchings', '0002_alter_matching_leader_alter_matching_matzip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='matzip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matzips.matzip'),
        ),
    ]
