# Generated by Django 4.0.6 on 2022-08-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('matchings', '0003_alter_matching_leader_alter_matching_matzip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='date',
        ),
        migrations.AlterField(
            model_name='matching',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='matching',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchings.matching')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
