# Generated by Django 4.0.6 on 2022-08-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0005_matching_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='duration',
            field=models.CharField(default='00시간00분', max_length=15),
        ),
    ]
