# Generated by Django 4.0.6 on 2022-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matzips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matzip',
            name='name',
            field=models.CharField(default='', max_length=60, null=True, unique=True),
        ),
    ]
