# Generated by Django 4.0.6 on 2022-09-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matzips', '0003_remove_matzip_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='matzip',
            name='matched',
            field=models.IntegerField(default=0),
        ),
    ]
