# Generated by Django 4.0.6 on 2022-09-09 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=18, unique=True)),
                ('major', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('rudeness', models.IntegerField(default=0)),
                ('noshow', models.IntegerField(default=0)),
                ('cancel', models.IntegerField(default=0)),
                ('matching_num', models.IntegerField(default=0)),
                ('matching_people', models.IntegerField(default=0)),
                ('is_disabled', models.BooleanField(default=False)),
                ('release_date', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('no-show', '노쇼'), ('rudeness', '비매너'), ('deception', '정보와 다른 사람')], default='', max_length=31)),
                ('reason', models.TextField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporter', to='profiles.profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='profiles.profile')),
            ],
        ),
    ]
