# Generated by Django 4.0.6 on 2022-07-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('member_pw', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=18, unique=True)),
                ('major', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('self_intro', models.CharField(blank=True, max_length=60, null=True)),
                ('rudeness', models.IntegerField(default=0)),
                ('noShow', models.IntegerField(default=0)),
                ('cancel', models.IntegerField(default=0)),
                ('total_matching_number', models.IntegerField(default=0)),
                ('total_matching_people', models.IntegerField(default=0)),
                ('disabled', models.BooleanField(default=False)),
                ('released_date', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
    ]
