# Generated by Django 4.0.6 on 2022-07-28 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=18, unique=True)),
                ('major', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('bio', models.CharField(blank=True, max_length=60, null=True)),
                ('rudeness', models.IntegerField(default=0)),
                ('noshow', models.IntegerField(default=0)),
                ('cancel', models.IntegerField(default=0)),
                ('matching_num', models.IntegerField(default=0)),
                ('matching_people', models.IntegerField(default=0)),
                ('is_disabled', models.BooleanField(default=False)),
                ('release_date', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
