# Generated by Django 4.0.6 on 2022-07-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='member',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='member',
            name='noShow',
        ),
        migrations.RemoveField(
            model_name='member',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='rudeness',
        ),
        migrations.RemoveField(
            model_name='member',
            name='total_matching_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='total_matching_people',
        ),
    ]
