# Generated by Django 4.0.6 on 2022-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_member_cancel_remove_member_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(max_length=18),
        ),
    ]
