# Generated by Django 4.0.6 on 2022-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='release_date',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
