# Generated by Django 4.0.6 on 2022-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
