# Generated by Django 4.0.6 on 2022-09-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='이메일주소')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 권한')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
