# Generated by Django 4.0.6 on 2022-07-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='이메일주소'),
        ),
    ]
